# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MXImageManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MXImageManager
  pod 'Masonry', '~> 1.1.0'
  pod 'YYWebImage', '~> 1.0.5'
  #pod 'YYImage', '~> 1.0.4'

end
