# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://cdn.cocoapods.org/'

target 'MXImageManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MXImageManagerDemo
  pod 'MXImageManager', :path => '../'
  
end
